name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      working-directory: ./Source

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out source
      uses: actions/checkout@v3

    # Install SDKs
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Build and Test    
    - name: Restore dependencies
      run: dotnet restore --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Build solution
      run: dotnet build --configuration Release --no-restore  --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Test solution
      run: dotnet test --configuration Release --no-restore --no-build --verbosity minimal
      working-directory: ${{env.working-directory}}
